- name: "NOTSCORED | 2.1.1.1 | PATCH | Ensure time synchronization is in use - service install"
  yum:
      name: "{{ amzn2cis_time_synchronization }}"
      state: present
  when:
      - amzn2cis_rule_2_1_1_1|bool
  tags:
      - level1
      - patch
      - rule_2.1.1.1

- name: "NOTSCORED | 2.1.1.1 | PATCH | Ensure time synchronization is in use - service start"
  service:
      name: "{{ amzn2cis_time_synchronization }}d"
      state: started
      enabled: yes
  when:
      - amzn2cis_rule_2_1_1_1|bool
  tags:
      - level1
      - patch
      - rule_2.1.1.1

- name: "NOTSCORED | 2.1.1.1 | PATCH | Ensure time synchronization is in use - service stop ntp"
  service:
      name: ntpd
      state: stopped
      enabled: no
  when:
      - amzn2cis_time_synchronization == "chrony" and ntpd_service_status.stdout == "loaded"
      - amzn2cis_rule_2_1_1_1|bool
  tags:
      - level1
      - patch
      - rule_2.1.1.1

- name: "NOTSCORED | 2.1.1.1 | PATCH | Ensure time synchronization is in use - service stop chrony"
  service:
      name: chronyd
      state: stopped
      enabled: no
  ignore_errors: yes
  when:
      - amzn2cis_time_synchronization == "ntp" and chronyd_service_status.stdout == "loaded"
      - amzn2cis_rule_2_1_1_1|bool
  tags:
      - level1
      - patch
      - rule_2.1.1.1

- name: "SCORED | 2.1.1.2 | PATCH | Ensure ntp is configured | modify /etc/ntp.conf"
  template:
      src: ntp.conf.j2
      dest: /etc/ntp.conf
      owner: root
      group: root
      mode: 0644
  when:
      - amzn2cis_time_synchronization == "ntp"
      - amzn2cis_rule_2_1_1_2|bool
  tags:
      - level1
      - patch
      - rule_2.1.1.2

- name: "SCORED | 2.1.1.2 | PATCH | Ensure ntp is configured | modify /etc/sysconfig/ntpd"
  lineinfile:
      dest: /etc/sysconfig/ntpd
      regexp: "^(#)?OPTIONS"
      line: "OPTIONS=\"-u ntp:ntp\""
  when:
      - amzn2cis_time_synchronization == "ntp"
      - amzn2cis_rule_2_1_1_2|bool
  tags:
      - level1
      - patch
      - rule_2.1.1.2

- name: "SCORED | 2.1.1.2 | PATCH | Ensure ntp is configured | modify /usr/lib/systemd/system/ntpd.service"
  lineinfile:
      dest: /usr/lib/systemd/system/ntpd.service
      regexp: "^(#)?ExecStart"
      line: "ExecStart=/usr/sbin/ntpd -u ntp:ntp $OPTIONS"
  when:
      - amzn2cis_time_synchronization == "ntp"
      - amzn2cis_rule_2_1_1_2|bool
  tags:
      - level1
      - patch
      - rule_2.1.1.2

- name: "SCORED | 2.1.1.3 | PATCH | Ensure chrony is configured"
  template:
      src: chrony.conf.j2
      dest: /etc/chrony.conf
      owner: root
      group: root
      mode: 0644
  when:
      - amzn2cis_time_synchronization == "chrony"
      - amzn2cis_rule_2_1_1_3|bool
  tags:
      - level1
      - patch
      - rule_2.1.1.3

- name: "SCORED | 2.1.1.3 | PATCH | Ensure chrony is configured | modify /etc/sysconfig/chronyd | 1"
  lineinfile:
      dest: /etc/sysconfig/chronyd
      regexp: "^(#)?OPTIONS"
      line: "OPTIONS=\"-u chrony\""
      state: present
      create: yes
  when:
      - amzn2cis_time_synchronization == "chrony"
      - amzn2cis_rule_2_1_1_3|bool
  tags:
      - level1
      - patch
      - rule_2.1.1.3

- name: "SCORED | 2.1.2 | PATCH | Ensure X Window System is not installed"
  yum:
      state: absent
      name:
          - "@X Window System"
          - "xorg-x11*"
  when:
      - not amzn2cis_xwindows_required
      - amzn2cis_rule_2_2_2|bool
  tags:
      - level1
      - scored
      - xwindows
      - patch
      - rule_2.2.2

- name: "SCORED | 2.1.3 | PATCH | Ensure Avahi Server is not enabled"
  service:
      name: avahi-daemon
      state: stopped
      enabled: no
  when:
      - not amzn2cis_avahi_server
      - avahi_service_status.stdout == "loaded"
      - amzn2cis_rule_2_1_3|bool
  tags:
      - level1
      - scored
      - avahi
      - services
      - patch
      - rule_2.1.3

- name: "SCORED | 2.1.4 | PATCH | Ensure CUPS is not enabled"
  service:
      name: cups
      state: stopped
      enabled: no
  when:
      - not amzn2cis_cups_server
      - cups_service_status.stdout == "loaded"
      - amzn2cis_rule_2_1_4|bool
  tags:
      - level1
      - scored
      - cups
      - services
      - patch
      - rule_2.1.4

- name: "SCORED | 2.1.5 | PATCH | Ensure DHCP Server is not enabled"
  service:
      name: dhcpd
      state: stopped
      enabled: no
  when:
      - not amzn2cis_dhcp_server
      - dhcpd_service_status.stdout == "loaded"
      - amzn2cis_rule_2_1_5|bool
  tags:
      - level1
      - scored
      - dhcp
      - services
      - patch
      - rule_2.1.5

- name: "SCORED | 2.1.6 | PATCH | Ensure LDAP server is not enabled"
  service:
      name: slapd
      state: stopped
      enabled: no
  when:
      - not amzn2cis_ldap_server
      - slapd_service_status.stdout == "loaded"
      - amzn2cis_rule_2_1_6|bool
  tags:
      - level1
      - scored
      - ldap
      - services
      - patch
      - rule_2.1.6

- name: "SCORED | 2.1.7 | PATCH | Ensure NFS and RPC are not enabled"
  service:
      name: nfs
      state: stopped
      enabled: no
  when:
      - not amzn2cis_nfs_rpc_server
      - nfs_service_status.stdout == "loaded"
      - amzn2cis_rule_2_1_7|bool
  tags:
      - level1
      - scored
      - nfs
      - rpc
      - services
      - patch
      - rule_2.1.7

- name: "SCORED | 2.1.7 | PATCH | Ensure NFS and RPC are not enabled"
  service:
      name: nfs-server
      state: stopped
      enabled: no
  when:
      - not amzn2cis_nfs_rpc_server
      - nfs_service_status.stdout == "loaded"
      - amzn2cis_rule_2_1_7|bool
  tags:
      - level1
      - scored
      - nfs
      - rpc
      - services
      - patch
      - rule_2.1.7

- name: "SCORED | 2.1.7 | PATCH | Ensure RPC is not enabled"
  service:
      name: rpcbind
      state: stopped
      enabled: no
  when:
      - not amzn2cis_nfs_rpc_server
      - rpcbind_service_status.stdout == "loaded"
      - amzn2cis_rule_2_1_7|bool
  tags:
      - level1
      - scored
      - nfs
      - rpc
      - services
      - patch
      - rule_2.1.7

- name: "SCORED | 2.1.8 | PATCH | Ensure DNS Server is not enabled"
  service:
      name: named
      state: stopped
      enabled: no
  when:
      - not amzn2cis_named_server
      - named_service_status.stdout == "loaded"
      - amzn2cis_rule_2_1_8|bool
  tags:
      - level1
      - patch
      - rule_2.1.8

- name: "SCORED | 2.1.9 | PATCH | Ensure FTP Server is not enabled"
  service:
      name: vsftpd
      state: stopped
      enabled: no
  when:
      - not amzn2cis_vsftpd_server
      - vsftpd_service_status.stdout == "loaded"
      - amzn2cis_rule_2_1_9|bool
  tags:
      - level1
      - patch
      - rule_2.1.9

- name: "SCORED | 2.1.10 | PATCH | Ensure HTTP server is not enabled"
  service:
      name: httpd
      state: stopped
      enabled: no
  when:
      - not amzn2cis_httpd_server
      - httpd_service_status.stdout == "loaded"
      - amzn2cis_rule_2_1_10|bool
  tags:
      - level1
      - patch
      - rule_2.1.10

- name: "SCORED | 2.1.11 | PATCH | Ensure IMAP and POP3 server is not enabled"
  service:
      name: dovecot
      state: stopped
      enabled: no
  when:
      - not amzn2cis_dovecot_server
      - dovecot_service_status.stdout == "loaded"
      - amzn2cis_rule_2_1_11|bool
  tags:
      - level1
      - patch
      - rule_2.1.11

- name: "SCORED | 2.1.12 | PATCH | Ensure Samba is not enabled"
  service:
      name: smb
      state: stopped
      enabled: no
  when:
      - not amzn2cis_smb_server
      - smb_service_status.stdout == "loaded"
      - amzn2cis_rule_2_1_12|bool
  tags:
      - level1
      - patch
      - rule_2.1.12

- name: "SCORED | 2.1.13 | PATCH | Ensure HTTP Proxy Server is not enabled"
  service:
      name: squid
      state: stopped
      enabled: no
  when:
      - not amzn2cis_squid_server
      - squid_service_status.stdout == "loaded"
      - amzn2cis_rule_2_2_13|bool
  tags:
      - level1
      - patch
      - rule_2.1.13

- name: "SCORED | 2.1.14 | PATCH | Ensure SNMP Server is not enabled"
  service:
      name: snmpd
      state: stopped
      enabled: no
  when:
      - not amzn2cis_snmp_server
      - snmpd_service_status.stdout == "loaded"
      - amzn2cis_rule_2_1_14|bool
  tags:
      - level1
      - patch
      - rule_2.1.14

- name: "SCORED | 2.1.15 | PATCH | Ensure mail transfer agent is configured for local-only mode"
  lineinfile:
      dest: /etc/postfix/main.cf
      regexp: "^(#)?inet_interfaces"
      line: "inet_interfaces = localhost"
  when:
      - not amzn2cis_is_mail_server
      - postfix_installed.rc == 0
      - amzn2cis_rule_2_1_15|bool
  tags:
      - level1
      - patch
      - rule_2.1.15

- name: "SCORED | 2.1.16 | PATCH | Ensure NIS Server is not enabled"
  service:
      name: ypserv
      state: stopped
      enabled: no
  when:
      - not amzn2cis_nis_server
      - ypserv_service_status.stdout == "loaded"
      - amzn2cis_rule_2_2_16|bool
  tags:
      - level1
      - patch
      - rule_2.1.16

- name: "SCORED | 2.1.17 | PATCH | Ensure rsh server is not enabled | rsh"
  service:
      name: rsh.socket
      state: stopped
      enabled: no
  when:
      - not amzn2cis_rsh_server
      - rsh_service_status.stdout == "loaded"
      - amzn2cis_rule_2_1_17|bool
  tags:
      - level1
      - patch
      - rule_2.1.17

- name: "SCORED | 2.1.17 | PATCH | Ensure rsh server is not enabled | rlogin"
  service:
      name: rlogin.socket
      state: stopped
      enabled: no
  when:
      - not amzn2cis_rsh_server
      - rlogin_service_status.stdout == "loaded"
      - amzn2cis_rule_2_1_17|bool
  tags:
      - level1
      - patch
      - rule_2.1.17

- name: "SCORED | 2.1.17 | PATCH | Ensure rsh server is not enabled | rexec"
  service:
      name: rexec.socket
      state: stopped
      enabled: no
  when:
      - not amzn2cis_rsh_server
      - rexec_service_status.stdout == "loaded"
      - amzn2cis_rule_2_1_17|bool
  tags:
      - level1
      - patch
      - rule_2.1.17

- name: "SCORED | 2.1.18 | PATCH | Ensure telnet server is not enabled"
  service:
      name: telnet
      state: stopped
      enabled: no
  when:
      - not amzn2cis_telnet_server
      - telnet_service_status.stdout == "loaded"
      - amzn2cis_rule_2_1_18|bool
  tags:
      - level1
      - patch
      - rule_2.1.18

- name: "SCORED | 2.1.19 | PATCH | Ensure tftp server is not enabled"
  service:
      name: tftp
      state: stopped
      enabled: no
  when:
      - not amzn2cis_tftp_server
      - tftp_service_status.stdout == "loaded"
      - amzn2cis_rule_2_1_19|bool
  tags:
      - level1
      - scored
      - insecure_services
      - tftp
      - patch
      - rule_2.1.19

- name: "SCORED | 2.1.20 | PATCH | Ensure rsync service is not enabled "
  service:
      name: rsyncd
      state: stopped
      enabled: no
  when:
      - not amzn2cis_rsyncd_server
      - rsyncd_service_status.stdout == "loaded"
      - amzn2cis_rule_2_1_20|bool
  tags:
      - level1
      - patch
      - rule_2.1.20

- name: "SCORED | 2.1.21 | PATCH | Ensure talk server is not enabled"
  service:
      name: ntalk
      state: stopped
      enabled: no
  when:
      - not amzn2cis_ntalk_server
      - ntalk_service_status.stdout == "loaded"
      - amzn2cis_rule_2_2_21|bool
  tags:
      - level1
      - patch
      - rule_2.1.21

- name: "SCORED | 2.2.1 | PATCH | Ensure NIS Client is not installed"
  yum:
      name: ypbind
      state: absent
  when:
      - not amzn2cis_ypbind_required
      - amzn2cis_rule_2_2_1|bool
  tags:
      - level1
      - patch
      - rule_2.2.1

- name: "SCORED | 2.2.2 | PATCH | Ensure rsh client is not installed"
  yum:
      name: rsh
      state: absent
  when:
      - not amzn2cis_rsh_required
      - amzn2cis_rule_2_2_2|bool
  tags:
      - level1
      - patch
      - rule_2.2.2

- name: "SCORED | 2.2.3 | PATCH | Ensure talk client is not installed"
  yum:
      name: talk
      state: absent
  when:
      - not amzn2cis_talk_required
      - amzn2cis_rule_2_2_3|bool
  tags:
      - level1
      - patch
      - rule_2.2.3

- name: "SCORED | 2.2.4 | PATCH | Ensure telnet client is not installed"
  yum:
      name: telnet
      state: absent
  when:
      - not amzn2cis_telnet_required
      - amzn2cis_rule_2_2_4|bool
  tags:
      - level1
      - patch
      - rule_2.2.4

- name: "SCORED | 2.2.5 | PATCH | Ensure LDAP client is not installed"
  yum:
      name: openldap-clients
      state: absent
  when:
      - not amzn2cis_openldap_clients_required
      - amzn2cis_rule_2_2_5|bool
  tags:
      - level1
      - patch
      - rule_2.2.5
